- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/gnome.yml
    - include_tasks: tasks/thingspeak.yml
    - include_tasks: tasks/syncthing.yml
    - include_tasks: tasks/brave-browser.yml
    - include_tasks: tasks/keybase.yml
    - include_tasks: tasks/plexserver.yml

  roles:
    - role: charliemaiors.rclone_ansible
    - role: nbigot.ansible-fail2ban

  vars:
    fail2ban_services:
      - name: ssh
        port: 22
