- name: install cron job (ansible-pull)
  cron:
    user="ansible"
    name="ansible provision"
    minute="*/15"
    job="/usr/bin/ansible-pull -o -U https://github.com/ajft/ansible-pc.git > $HOME/ansible.log 2>&1"

- name: Creates my custom path, default /usr/bin:/bin is insufficient
  cron:
    user="ajft"
    name="PATH"
    env="yes"
    job="/snap/bin:/home/ajft/bin:/home/arch/Linux-x86_64/bin:/usr/bin:/bin"

- name: install cron job (ajft-reboot)
  cron: user="ajft" name="ajft reboot" special_time="reboot" job="$HOME/bin/cron.reboot"

- name: install cron job (ajft-hourly)
  cron: user="ajft" name="ajft hourly" special_time="hourly" job="$HOME/bin/cron.hourly"

- name: install cron job (ajft-daily)
  cron: user="ajft" name="ajft daily" special_time="daily" job="$HOME/bin/cron.daily"

- name: install cron job (ajft-weekly)
  cron: user="ajft" name="ajft weekly" special_time="weekly" job="$HOME/bin/cron.weekly"

- name: install cron job (ajft-monthly)
  cron: user="ajft" name="ajft monthly" special_time="monthly" job="$HOME/bin/cron.monthly"

- name: install cron job (root-hourly)
  cron: user="root" name="root hourly" special_time="hourly" job="$HOME/bin/cron.hourly"

- name: install cron job (root-daily)
  cron: user="root" name="root daily" special_time="daily" job="$HOME/bin/cron.daily"

# linux counter project EOL https://en.wikipedia.org/wiki/Linux_Counter
# - name: install cron job (ajft-linuxcounter)
#  cron:
#    user="ajft"
#    name="linux counter project"
#    job="$HOME/bin/lico-update.sh -m > /dev/null 2>&1"
#    minute: "1"
#    hour: "21"
#    weekday: "4"
