- name: install cron job (ansible-pull)
  cron: user="ansible" name="ansible provision" minute="*/15" job="/usr/bin/ansible-pull -o -U https://github.com/ajft/ansible-pc.git > /dev/null"

- name: install cron job (ajft-reboot)
  cron: user="ajft" name="ajft reboot" special_time="reboot" job="$HOME/bin/cron.reboot"

- name: install cron job (ajft-hourly)
  cron: user="ajft" name="ajft hourly" special_time="hourly" job="$HOME/bin/cron.hourly"

- name: install cron job (ajft-monthly)
  cron: user="ajft" name="ajft monthly" special_time="monthly" job="$HOME/bin/cron.monthly"

- name: install cron job (root-hourly)
  cron: user="root" name="root hourly" special_time="hourly" job="$HOME/bin/cron.hourly"

- name: install cron job (root-daily)
  cron: user="root" name="root daily" special_time="daily" job="$HOME/bin/cron.daily"

# linux counter project EOL https://en.wikipedia.org/wiki/Linux_Counter
# - name: install cron job (ajft-linuxcounter)
#  cron:
#    user="ajft"
#    name="linux counter project"
#    job="$HOME/bin/lico-update.sh -m > /dev/null 2>&1"
#    minute: "1"
#    hour: "21"
#    weekday: "4"
