- name: Add the keybase PGP key
  apt_key:
    url: https://keybase.io/docs/server_security/code_signing_key.asc
    state: present

- name: Install apt repositories
  apt_repository:
    repo: deb http://prerelease.keybase.io/deb stable main
    state: present
    filename: keybase

- name: Install keybase
  apt:
    pkg:
      - keybase
