- name: Install deb packages
  apt:
    pkg:
    - aptitude
    - borgbackup
    - calibre
    - cpanminus
    - ddclient
    - etckeeper
    - fonts-firacode
    - fonts-powerline
    - git
    - gkrellm
    - gnuplot
    - guvcview
    - htop
    - imagemagick
    - ibritish-large
    - ispell
    - ldap-utils
    - ledger
    - libdatetime-format-strptime-perl
    - libgd-perl
    - libimage-exiftool-perl
    - libpango1.0-0 # required by dropbox
    - libqt5sql5 # required by rescuetime
    - libsqlite3-dev # required by camlistore
    - mailutils
    - mercurial
    - mono-runtime
    - mosquitto
    - mosquitto-clients
    - mrtg
    - net-tools
    - netcat
    - python3-pip
    - rrdtool
    - screen
    - sqlite
    - subversion
    - tmux
    - tor
    - uptimed
    - vlc
    - xplanet

- name: Install snap packages
  snap:
    name:
      - gnome-system-monitor
      - guvcview
      - mutt
      - signal-desktop
      - spotify
      - zoom-client

- name: Snaps that need classic confinement
  snap:
    name:
      - ruby
    classic: yes
