- name: Install deb packages
  apt:
    pkg:
    - fonts-powerline
    - htop
    - screen
    - tmux

- name: Install snap packages
  snap:
    name:
      - gnome-system-monitor
      - signal-desktop
