- name: Install deb packages
  apt:
    pkg:
    - fonts-firacode
    - fonts-powerline
    - git
    - svn
    - mercurial
    - htop
    - screen
    - tmux
    - uptimed

- name: Install snap packages
  snap:
    name:
      - gnome-system-monitor
      - signal-desktop
