- name: Install deb packages
  apt:
    pkg:
    - aptitude
    - borgbackup
    - fonts-firacode
    - fonts-powerline
    - git
    - gkrellm
    - gnuplot
    - htop
    - ledger
    - libimage-exiftool-perl
    - libpango1.0-0 # required by dropbox
    - mailutils
    - mercurial
    - screen
    - subversion
    - tmux
    - uptimed

- name: Install snap packages
  snap:
    name:
      - gnome-system-monitor
      - mutt
      - signal-desktop

- name: Snaps that need classic confinement
  snap:
    name:
      - ruby
    classic: yes
