- name: Add the Syncthing PGP key
  apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Install apt repositories
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
    filename: syncthing

- name: Install syncthing
  apt: name=syncthing

